In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('IRIS.csv')

In [2]:
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm   
0      1            5.1           3.5            1.4           0.2  \
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [3]:
X=df.drop(["Species"],axis=1)

In [4]:
Y=df ["Species"]

In [5]:
from sklearn.preprocessing import MinMaxScaler
Scaler=MinMaxScaler()
X_Scaled=Scaler.fit_transform(X)

In [6]:
X_Scaled

array([[0.        , 0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.00671141, 0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.01342282, 0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.02013423, 0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.02684564, 0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.03355705, 0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.04026846, 0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.04697987, 0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.05369128, 0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.06040268, 0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.06711409, 0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.0738255 , 0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.08053691, 0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.08724832, 0.        , 0.41666667, 0.01694915, 0.        ],
       [0.09395973, 0.41666667, 0.

In [7]:
import seaborn as sns
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=12)

In [8]:
X_train

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
14    15            5.8           4.0            1.2           0.2
62    63            6.0           2.2            4.0           1.0
98    99            5.1           2.5            3.0           1.1
26    27            5.0           3.4            1.6           0.4
8      9            4.4           2.9            1.4           0.2
..   ...            ...           ...            ...           ...
76    77            6.8           2.8            4.8           1.4
3      4            4.6           3.1            1.5           0.2
130  131            7.4           2.8            6.1           1.9
134  135            6.1           2.6            5.6           1.4
75    76            6.6           3.0            4.4           1.4

[112 rows x 5 columns]

In [9]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X_test=std.fit_transform(X_test)
X_test

array([[-0.66250768, -0.97960106,  0.86716764, -1.26274317, -1.12684585],
       [ 1.7180284 ,  0.67766923, -1.25879174,  0.84083135,  1.05507223],
       [-0.70742346, -1.74449504, -0.19581205, -1.26274317, -1.26321573],
       [ 0.66250768, -0.08722475, -0.62100392,  0.32915106,  0.23685295],
       [ 1.65065473,  1.31508088,  0.22937983,  1.35251164,  1.60055175],
       [ 1.04429177,  0.93263389, -0.19581205,  1.12509818,  0.91870235],
       [ 1.76294417,  0.5501869 ,  0.6545717 ,  1.06824481,  1.60055175],
       [-0.68496557, -0.85211873,  0.6545717 , -1.14903644, -1.26321573],
       [ 1.47099163,  2.46242185, -0.19581205,  1.46621837,  1.60055175],
       [-1.04429177, -0.85211873,  0.44197577, -1.0353297 , -0.85410609],
       [-0.07860261, -0.21470708, -0.19581205,  0.55656452,  0.50959271],
       [-1.20149698, -0.46967174,  1.71755139, -1.26274317, -0.99047597],
       [-0.86462867, -0.46967174,  0.6545717 , -1.14903644, -0.99047597],
       [-1.08920755, -0.85211873,  1.2

In [10]:
 X_train=std.fit_transform(X_train)

In [11]:
X_train

array([[-1.45511942, -0.08211928,  2.29631909, -1.50722507, -1.33211514],
       [-0.3321332 ,  0.15677318, -2.01408993,  0.09177961, -0.29060103],
       [ 0.51010646, -0.91824291, -1.29568842, -0.47929349, -0.16041177],
       [-1.17437287, -1.03768914,  0.85951608, -1.27879583, -1.07173661],
       [-1.5954927 , -1.75436653, -0.33781975, -1.39301045, -1.33211514],
       [-1.33814169, -0.91824291,  1.81738475, -1.33590314, -1.20192587],
       [-1.50191051, -1.2765816 , -0.09835259, -1.39301045, -1.4623044 ],
       [-1.54870161, -0.55990421,  1.57791759, -1.33590314, -1.33211514],
       [-0.70646194, -0.91824291,  1.81738475, -1.27879583, -1.33211514],
       [-0.9404174 , -0.44045798,  1.09898325, -1.45011776, -1.33211514],
       [ 1.11839067,  0.9928968 ,  0.62004892,  1.06260387,  1.14148086],
       [-1.61888825, -1.03768914,  0.85951608, -1.33590314, -1.33211514],
       [ 1.30555504,  0.63455811, -0.57728692,  1.00549656,  1.27167012],
       [ 0.20596436,  0.15677318,  0.8

In [12]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,Y_train)

GaussianNB()

In [13]:
Y_pred=model.predict(X_test)
Y_pred

array(['Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor'], dtype='<U15')

In [16]:
 from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,classification_report

In [17]:
acc_s=accuracy_score(Y_pred,Y_test)
acc_s

0.9736842105263158

In [18]:
print(confusion_matrix(Y_test,Y_pred))

[[15  0  0]
 [ 0 11  1]
 [ 0  0 11]]


In [19]:
print(precision_score(Y_test,Y_pred,average='macro'))

0.9722222222222222


In [20]:
print(recall_score(Y_test,Y_pred,average='macro'))

0.9722222222222222


In [21]:
print(classification_report(Y_pred,Y_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.92      1.00      0.96        11
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        38
      macro avg       0.97      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38

